server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jktime_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

